# Generated by Django 6.0.1 on 2026-01-07 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Где пользователь будет выполнять привычку (например: дома, парк, офис).', max_length=255, verbose_name='Место')),
                ('time', models.TimeField(help_text='Во сколько нужно выполнять привычку.', verbose_name='Время')),
                ('action', models.CharField(help_text='Формулировка привычки: что именно нужно сделать.', max_length=255, verbose_name='Действие')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Если True - это приятная привычка (награда), а не полезная.', verbose_name='Приятная привычка')),
                ('periodicity', models.PositiveSmallIntegerField(default=1, help_text='Как часто выполнять привычку (в днях). По умолчанию ежедневно (1).', verbose_name='Периодичность (дни)')),
                ('reward', models.CharField(blank=True, help_text='Чем наградить себя после выполнения (если не используется связанная привычка).', max_length=255, null=True, verbose_name='Вознаграждение')),
                ('duration', models.PositiveSmallIntegerField(help_text='Сколько секунд занимает выполнение. Должно быть не больше 120.', verbose_name='Время на выполнение (секунды)')),
                ('is_public', models.BooleanField(default=False, help_text='Если True - привычку видно в списке публичных привычек.', verbose_name='Публичная')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(help_text='Создатель привычки.', on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_habit', models.ForeignKey(blank=True, help_text='Приятная привычка-награда, которая выполняется после полезной.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_for', to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ('-created_at',),
            },
        ),
    ]
