# Generated by Django 5.2.10 on 2026-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка напоминания'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
